.TH "D:/doxygenintro Directory Reference" 3 "Fri May 21 2021" "Dividend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/doxygenintro Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBincl_optionsdiv\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdividenda\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdividenda\&.hpp\fP"
.br
.in -1c
