.TH "D:/doxygenintro/incl_optionsdiv/dividend.hpp" 3 "Fri May 21 2021" "Dividend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/doxygenintro/incl_optionsdiv/dividend.hpp
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBrole_type\fP { \fBPROPOSER\fP =1, \fBVOTER1\fP =2, \fBVOTER2\fP =3 }"
.br
.ti -1c
.RI "enum \fBroi_target_cap\fP { \fBITERATION\fP =1, \fBHORIZONTAL\fP =2, \fBVERTICAL\fP =3 }"
.br
.RI "1- iterative 2- horizontal 3- vertical "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBVERSION\fP = 'Version = 140 QA2'"
.br
.ti -1c
.RI "const std::string \fBfreeos_acct\fP = 'freeos'"
.br
.ti -1c
.RI "const std::string \fBfreeosconfig_acct\fP = 'freeosconfig'"
.br
.ti -1c
.RI "symbol_code \fBfreeos\fP = symbol_code('FREEOS')"
.br
.ti -1c
.RI "const name \fBtokencontra\fP = 'freeos'_n"
.br
.RI "Token contract (for inline transfers) "
.ti -1c
.RI "const name \fBdaoaccount\fP = 'freeosdaodao'_n"
.br
.RI "Organizational target DAO account\&. "
.ti -1c
.RI "const name \fBthis_account\fP = 'optionsdiv'_n"
.br
.ti -1c
.RI "const int \fBUNKNOWN_ITERATION\fP = 1"
.br
.ti -1c
.RI "const int \fBACTION_IGNORED\fP = 2"
.br
.ti -1c
.RI "const int \fBNON_FOUNDER\fP = 3"
.br
.ti -1c
.RI "const int \fBNFT_MINTED\fP = 4"
.br
.ti -1c
.RI "const int \fBNFT_REFUSED\fP = 5"
.br
.ti -1c
.RI "const int \fBNFT_CHOWN\fP = 6"
.br
.ti -1c
.RI "const int \fBITERATION_ZERO\fP = 7"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBrole_type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPROPOSER \fP\fP
.TP
\fB\fIVOTER1 \fP\fP
.TP
\fB\fIVOTER2 \fP\fP
.SH "Variable Documentation"
.PP 
.SS "const int ACTION_IGNORED = 2"

.SS "const name daoaccount = 'freeosdaodao'_n"

.PP
Organizational target DAO account\&. 
.SS "symbol_code freeos = symbol_code('FREEOS')"

.SS "const std::string freeos_acct = 'freeos'"

.SS "const std::string freeosconfig_acct = 'freeosconfig'"

.SS "const int ITERATION_ZERO = 7"

.SS "const int NFT_CHOWN = 6"

.SS "const int NFT_MINTED = 4"

.SS "const int NFT_REFUSED = 5"

.SS "const int NON_FOUNDER = 3"

.SS "const name this_account = 'optionsdiv'_n"

.SS "const name tokencontra = 'freeos'_n"

.PP
Token contract (for inline transfers) 
.SS "const int UNKNOWN_ITERATION = 1"

.SS "const std::string VERSION = 'Version = 140 QA2'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Dividend from the source code\&.
